const assert = require('node:assert/strict');
const {equipment, bonuses, objectDetails, objectAt} = require('../coworld/paintbot/inspector.js');
assert.equal(equipment({}), 'None');
assert.match(equipment({}, {sprayCan: true, sprayCooldown: 48, armor: 2}, true), /ready in 2.0s.*Armor · 2 \/ 3.*Uniform/);
assert.match(bonuses({hp: 3}, {elevation: 200, trench: 0, spread: 50}), /70%.*Elevation 2.0 m.*50% less.*cooldown: 3s/);
assert.match(bonuses({hp: 3}, {elevation: 0, trench: -1, spread: 125}), /25% more.*uphill/);
assert.doesNotMatch(bonuses({hp: 0}, {elevation: 200, trench: 0, spread: 50}), /70%|less/);
const state = {world: {tick: 120, controlHearts: [{owner: 1}], heartCaptures: [{team: 0, ticks: 24}], pickups: [{kind: 'armorPickup', readyAt: 240}]}, heartHeld: [48], heartValues: [5]};
let info = objectDetails({kind: 'heart', id: 0}, state);
assert.equal(info.title, 'Big heart 1');
assert.deepEqual(info.rows.slice(0, 3), [['Owner', 'Azure'], ['Held continuously', '2.0s'], ['Value', '5 points/s']]);
assert.match(info.rows[3][1], /Ember capturing · 2.0s remaining/);
state.world.controlHearts[0].owner = -1;
assert.equal(objectDetails({kind:'heart',id:0},state).rows[1][1], 'Unclaimed');
assert.match(objectDetails({kind:'pickup',id:0},state).rows[0][1], /Respawns in 5.0s/);
state.world.tick = 240;
assert.equal(objectDetails({kind:'pickup',id:0},state).rows[0][1], 'Available');
assert.equal(objectDetails({kind:'heart',id:4},state), null);
const rect = {left:100,top:50,width:1000,height:500};
const items = [{kind:'heart',id:0,bottom:[0.5,0.8],top:[0.5,0.2]}, {kind:'pickup',id:2,bottom:[0.7,0.5],top:[0.7,0.4]}];
assert.deepEqual(objectAt(items,rect,605,200),{kind:'heart',id:0});
assert.deepEqual(objectAt(items,rect,800,280),{kind:'pickup',id:2});
assert.equal(objectAt(items,rect,900,400),null);
assert.equal(objectAt([{kind:'heart',id:1,bottom:[-100,-100],top:[-100,-100]}],rect,100,50),null);
console.log('Paintbot inspector text, modifiers, durations, and object picking passed');
