#!/usr/bin/env python3
"""Generate coworld/paintbot/players/ffa_blind.bas, the kin-blind control for ffa.bas.

ffa_blind.bas is ffa.bas with every kinship read replaced: each `kin(x)` call becomes
`blindKin(x)`, an array that is 100 for the cog itself (r_ii = 1, as the engine's kin(selfId)
reads) and 0 for every other seat, so the bot treats all 15 others as strangers and still knows
which hearts and shouts are its own. Nothing else changes: same movement, targeting, hearts and
great-heart play. The incentive eval (tools/kin_eval.py --suite incentive) plays the two against
each other to ask whether acting on kinship pays under the Heartland rules.

    python tools/make_ffa_blind.py            rewrite ffa_blind.bas from ffa.bas
    python tools/make_ffa_blind.py --check    exit 1 if the committed file is stale
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "coworld/paintbot/players/ffa.bas"
TARGET = ROOT / "coworld/paintbot/players/ffa_blind.bas"

HEADER = (
    "' GENERATED by tools/make_ffa_blind.py from ffa.bas: do not edit. The kin-blind control:\n"
    "' every kin(x) reads blindKin(x) = 100 for this cog, 0 for all others (all strangers).\n"
)
KIN_CALL = re.compile(r"(?<![A-Za-z0-9_])kin\(")
DIM_ANCHOR = "dim drF(6)\n"
INIT_ANCHOR = "if started = 0 then\n  started = 1\n"


def blind(source: str) -> str:
    """The kin-blind program for an ffa.bas source text."""
    for anchor in (DIM_ANCHOR, INIT_ANCHOR):
        if source.count(anchor) != 1:
            raise SystemExit(f"ffa.bas no longer has exactly one {anchor!r}; update make_ffa_blind.py")
    out, count = KIN_CALL.subn("blindKin(", source)
    if count == 0:
        raise SystemExit("ffa.bas has no kin( calls; nothing to blind")
    out = out.replace(DIM_ANCHOR, DIM_ANCHOR + "dim blindKin(16)\n")
    out = out.replace(INIT_ANCHOR, INIT_ANCHOR + "  blindKin(selfId) = 100\n")
    return HEADER + out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if ffa_blind.bas is not up to date")
    args = parser.parse_args()
    wanted = blind(SOURCE.read_text())
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != wanted:
            print(f"{TARGET.relative_to(ROOT)} is stale: run python tools/make_ffa_blind.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(wanted)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
