' Paintbot PW Jev baseline: the BASIC baseline steered by the host advisor oracle (Jev).
' Generated by coworld/paintbot/tools/make_jev_baseline.py from players/base.bas; edit the
' generator, not this file.
' Reflexes stay in code. Jev picks the squad objective from a code-ranked list and, for a cog
' in danger, where to retreat to; its survival estimate moves the break-off threshold. One cog
' per squad asks and relays by shout. Without an oracle this file plays exactly like the baseline.
' Baseline notes follow. Every cog runs this file on its own: no shared memory, fog-gated
' vision, int32 only. Territory play is built from four habits that measurably win fights:
'   1. lead the target by the full gun windup and cancel out our own movement,
'   2. never walk in a straight line while an opponent can see us,
'   3. move in squads of four that agree on a heart without talking,
'   4. refuse a fight we are visibly losing.
' Budget: 20,000 instructions per decision; an overrun disables the cog, so every loop here
' is bounded by the 16 seats, the heart count, or a fixed iteration count.
dim avoidUntil(16)
dim pickupMemoryX(32)
dim pickupMemoryY(32)
dim pickupMemoryKind(32)
dim pickupMemoryTick(32)
dim oldX(16)
dim oldY(16)
dim lastSeen(16)
' Jev layer knowledge: enemy sighting map (16 x 10 cells of 5 m), heart history, candidates
' that outlive an ask until its answer lands, retreat points.
dim enemyCellTick(160)
dim heartOwnerPrev(16)
dim heartThreat(16)
dim candHeart(6)
dim candKind(6)
dim candText(6)
dim candLabel(6)
dim retX(4)
dim retY(4)

' Integer square root by Newton's method from above. 23170^2 exceeds any squared map distance.
sub isqrt(n)
  root = 0
  if n <= 0 then
    exit sub
  end if
  root = 23170
  guess = (root + n / root) / 2
  iterations = 0
  while guess < root and iterations < 24
    root = guess
    guess = (root + n / root) / 2
    iterations = iterations + 1
  wend
end sub

' Small linear congruential generator; every product stays far inside int32.
sub nextRandom()
  rngState = (rngState * 75 + 74) mod 65537
end sub

' Pick the next dodge leg: mostly reverse across the line to the threat, keep some progress
' toward the goal, and hold the leg for legTicks so a shot that starts now flies true.
sub planLeg(minTicks, maxTicks)
  nextRandom()
  if rngState mod 5 <> 0 then
    zig = 0 - zig
  end if
  if zig = 0 then
    zig = 1
  end if
  nextRandom()
  legTicks = minTicks + rngState mod (maxTicks - minTicks + 1)
  tx = threatX - selfX
  ty = threatY - selfY
  isqrt(tx * tx + ty * ty)
  legX = 0
  legY = 0
  if root > 0 then
    ' Perpendicular to the threat, scaled to 100.
    legX = (0 - ty) * 100 * zig / root
    legY = tx * 100 * zig / root
  end if
  if holding = 0 then
    fx = goalX - selfX
    fy = goalY - selfY
    isqrt(fx * fx + fy * fy)
    if root > 60 then
      legX = legX * 3 / 4 + fx * 100 / root
      legY = legY * 3 / 4 + fy * 100 / root
    end if
  end if
  isqrt(legX * legX + legY * legY)
  if root > 0 then
    legX = legX * 28 / root
    legY = legY * 28 / root
  end if
end sub

' Compass label for a displacement (y grows southward), into bear.
sub bearingOf(bx, by)
  ax = bx
  if ax < 0 then
    ax = 0 - ax
  end if
  ay = by
  if ay < 0 then
    ay = 0 - ay
  end if
  if ax > ay * 2 then
    bear = strNew("E")
    if bx < 0 then
      bear = strNew("W")
    end if
  else
    if ay > ax * 2 then
      bear = strNew("S")
      if by < 0 then
        bear = strNew("N")
      end if
    else
      if by < 0 then
        bear = strNew("NE")
        if bx < 0 then
          bear = strNew("NW")
        end if
      else
        bear = strNew("SE")
        if bx < 0 then
          bear = strNew("SW")
        end if
      end if
    end if
  end if
end sub

' "<m> m <bearing>" for a displacement from me, into line; the distance in units into whereD.
sub whereLine(bx, by)
  isqrt(bx * bx + by * by)
  whereD = root
  bearingOf(bx, by)
  line = strCat(strCat(strCatInt(strNew(""), root / 100), strNew(" m ")), bear)
end sub

' One heart as a candidate sentence with computed facts, into line; "H<j>" into label.
sub heartLine(j)
  label = strCatInt(strNew("H"), j)
  whereLine(controlX(j) - selfX, controlY(j) - selfY)
  myD = whereD
  if controlOwner(j) = selfTeam then
    line = strCat(strNew("ours, "), line)
  else
    if controlOwner(j) >= 0 then
      line = strCat(strNew("enemy-held, "), line)
    else
      line = strCat(strNew("neutral, "), line)
    end if
  end if
  ' Walking speed is 28 units a tick, 24 ticks a second.
  line = strCat(strCatInt(strCat(line, strNew(", reach in ")), myD / 672 + 1), strNew(" s"))
  if heartThreat(j) then
    line = strCat(line, strNew(", enemy seen near it in the last 5 s"))
  else
    line = strCat(line, strNew(", no enemy seen near it"))
  end if
  ' Did an enemy we saw in the last five seconds stand closer to it than we do?
  closer = 0
  e = 1 - selfTeam
  while e < 16
    if lastSeen(e) > 0 then
      if worldTick - lastSeen(e) < 120 then
        ex = oldX(e) - controlX(j)
        ey = oldY(e) - controlY(j)
        if ex * ex + ey * ey < myD * myD then
          closer = 1
        end if
      end if
    end if
    e = e + 2
  wend
  if closer then
    line = strCat(line, strNew(", an enemy was closer to it than I am"))
  end if
  if controlCaptureTeam(j) >= 0 then
    if controlCaptureTeam(j) = selfTeam then
      line = strCat(line, strNew(", we are capturing it"))
    else
      line = strCat(line, strNew(", enemy is capturing it now"))
    end if
  end if
  if controlPoints(j) > 1 then
    line = strCat(line, strNew(", big heart worth 5 points a second"))
  end if
  if j = otherSquadObj and worldTick - otherSquadTick < 240 then
    line = strCat(line, strNew(", our other squad is heading there"))
  end if
  if j = objective then
    line = strCat(line, strNew(", my squad's default"))
  end if
end sub

' One enemy in view as a sentence, into line; "E<i>" into label.
sub enemyLine(i)
  label = strCatInt(strNew("E"), i)
  whereLine(playerX(i) - selfX, playerY(i) - selfY)
  line = strCat(strCatInt(strCat(line, strNew(", hp ")), playerHp(i)), strNew("/3"))
  if playerCarrying(i) then
    line = strCat(line, strNew(", carrying our heart"))
  end if
  if i = nearSeat then
    if closing > 4 then
      line = strCat(line, strNew(", closing on me"))
    end if
    if closing < -4 then
      line = strCat(line, strNew(", moving away"))
    end if
  end if
end sub

if started = 0 then
  started = 1
  rngState = selfId * 4099 + 977
  zig = 1
  if selfId mod 4 >= 2 then
    zig = -1
  end if
  lastX = selfX
  lastY = selfY
end if
myVX = selfX - lastX
myVY = selfY - lastY
if myVX > 60 or myVX < -60 or myVY > 60 or myVY < -60 then
  ' A respawn teleports us; that is not a velocity.
  myVX = 0
  myVY = 0
  gunWait = 0
end if
if gunWait > 0 then
  gunWait = gunWait - 1
end if

' Drop an unreachable assignment after three seconds without meaningful progress.
if worldTick mod 72 = 0 then
  dxProgress = selfX - progressX
  dyProgress = selfY - progressY
  if dxProgress * dxProgress + dyProgress * dyProgress < 40000 and objective >= 0 and objective < 16 then
    dxHeart = controlX(objective) - selfX
    dyHeart = controlY(objective) - selfY
    if dxHeart * dxHeart + dyHeart * dyHeart > 160000 then
      avoidUntil(objective) = worldTick + 360
    end if
  end if
  progressX = selfX
  progressY = selfY
end if

' Opponents and teammates in view. Every query is fog gated.
best = -1
bestCost = 2147483647
thief = -1
foesNear = 0
friendsNear = 1
foeSumX = 0
foeSumY = 0
foesSeen = 0
i = 0
while i < 16
  if i <> selfId and visible(i) then
    dx = playerX(i) - selfX
    dy = playerY(i) - selfY
    d2 = dx * dx + dy * dy
    if i mod 2 <> selfTeam then
      cost = d2 - (3 - playerHp(i)) * 160000
      if playerCarrying(i) then
        cost = cost - 2500000
        thief = i
      end if
      if cost < bestCost and d2 <= 27562500 then
        best = i
        bestCost = cost
      end if
      foesSeen = foesSeen + 1
      foeSumX = foeSumX + playerX(i)
      foeSumY = foeSumY + playerY(i)
      if d2 < 6760000 then
        foesNear = foesNear + 1
      end if
    else
      if d2 < 1440000 then
        friendsNear = friendsNear + 1
      end if
    end if
  end if
  i = i + 1
wend

' ---- Jev layer: knowledge kept for the oracle, events, and the last answer. ----
if jevInit = 0 then
  jevInit = 1
  ' Switches (1 on, 0 off). Defaults from 32 paired games per arm vs the baseline (margin at
  ' 1,200 ticks): leader asks + wide list +17.1 +/- 6.1; every cog asking -2.1; retreat as a
  ' choice -3.6 and the survival dial -5.2 relative to the core, so both stay off.
  useObjective = 1
  useRetreat = 0
  useDial = 0
  useRelay = 1
  useLeader = 1
  useExamples = 1
  ' Wider objective list (a guard option, the big heart, a strike on an enemy heart). Off: it looked
  ' fine at 1,200 ticks (+17.1) but loses full-length games (1/8 against 8/8 without it).
  useWide = 0
  ' Honesty controls: a random candidate, or the cheapest candidate with no enemy seen near it.
  useShuffle = 0
  useRule = 0
  ' Knobs (tuned in daveey/cogamer, cogames/paintbot/jev/scripts/tune.py).
  kAskDelay = 48
  kHold = 120
  kConf = 300
  kMargin = 0
  kCand = 3
  kRetreatHold = 72
  kDialLow = 350
  kDialHigh = 750
  kLeaderWait = 120
  retreatDial = 1
  jevObjective = -1
  jevGuard = -1
  otherSquadObj = -1
  otherSquadTick = -1000
  lastAskTick = -1000
  lastAnswerTick = -1000
  lastDirectiveTick = 0
  hpPrev = selfHp
  livesPrev = livesLeft
  j = 0
  while j < 16
    heartOwnerPrev(j) = -2
    j = j + 1
  wend
end if
jevEvent = 0
selfEvent = 0
mySquad = ((selfId / 2) mod 8) / 4
mySeat = ((selfId / 2) mod 8) mod 4
' Enemy sighting map, nearest enemy and its closing speed.
nearSeat = -1
nearD2 = 2147483647
i = 1 - selfTeam
while i < 16
  if visible(i) then
    cx = (playerX(i) + 800) / 500
    cy = (playerY(i) + 400) / 500
    if cx >= 0 and cx < 16 and cy >= 0 and cy < 10 then
      enemyCellTick(cy * 16 + cx) = worldTick + 1
    end if
    dx = playerX(i) - selfX
    dy = playerY(i) - selfY
    if dx * dx + dy * dy < nearD2 then
      nearD2 = dx * dx + dy * dy
      nearSeat = i
    end if
  end if
  i = i + 2
wend
closing = 0
if nearSeat >= 0 then
  if lastSeen(nearSeat) = worldTick - 1 then
    ox = oldX(nearSeat) - lastX
    oy = oldY(nearSeat) - lastY
    isqrt(ox * ox + oy * oy)
    prevD = root
    isqrt(nearD2)
    closing = prevD - root
  end if
end if
' Public score integral (points per owned heart per second, kept x24), heart counts, flips.
ownedCount = 0
enemyCount = 0
neutralCount = 0
j = 0
while j < heartCount() and j < 16
  own = controlOwner(j)
  if own = selfTeam then
    ourScore24 = ourScore24 + controlPoints(j)
    ownedCount = ownedCount + 1
  else
    if own >= 0 then
      theirScore24 = theirScore24 + controlPoints(j)
      enemyCount = enemyCount + 1
    else
      neutralCount = neutralCount + 1
    end if
  end if
  if heartOwnerPrev(j) <> own then
    if heartOwnerPrev(j) <> -2 then
      jevEvent = 1
      lastFlipTick = worldTick + 1
    end if
    heartOwnerPrev(j) = own
  end if
  j = j + 1
wend
' Threat near each heart from the sighting map, refreshed twice a second.
if worldTick mod 12 = selfId mod 12 then
  j = 0
  while j < heartCount() and j < 16
    heartThreat(j) = 0
    cx = (controlX(j) + 800) / 500
    cy = (controlY(j) + 400) / 500
    ny = cy - 1
    while ny <= cy + 1
      nx = cx - 1
      while nx <= cx + 1
        if nx >= 0 and nx < 16 and ny >= 0 and ny < 10 then
          if enemyCellTick(ny * 16 + nx) > 0 and enemyCellTick(ny * 16 + nx) > worldTick - 120 then
            heartThreat(j) = 1
          end if
        end if
        nx = nx + 1
      wend
      ny = ny + 1
    wend
    j = j + 1
  wend
end if
' Events: contact gained or lost and heart flips concern the squad; damage, death and being
' outnumbered concern this cog.
if foesSeen > 0 and foesSeenPrev = 0 then
  jevEvent = 1
  if firstContact = 0 then
    firstContact = worldTick + 1
  end if
end if
if foesSeen = 0 and foesSeenPrev > 0 then
  jevEvent = 1
end if
if selfHp < hpPrev then
  selfEvent = 1
  dmgTick = worldTick + 1
end if
if livesLeft < livesPrev then
  jevEvent = 1
  deathTick = worldTick + 1
end if
if foesNear > friendsNear and outnumberedPrev = 0 then
  selfEvent = 1
end if
outnumberedPrev = 0
if foesNear > friendsNear then
  outnumberedPrev = 1
end if
' Fights: one starts when a target appears and ends two seconds after the last one is seen.
if best >= 0 then
  if fightOn = 0 then
    fightOn = 1
    fightHp = selfHp
  end if
  fightLast = worldTick
else
  if fightOn = 1 and worldTick - fightLast > 48 then
    fightOn = 0
    won = 0
    if selfHp >= fightHp then
      won = 1
    end if
    fightsWon = fightsWon + won
    fightCount = fightCount + 1
  end if
end if
foesSeenPrev = foesSeen
hpPrev = selfHp
livesPrev = livesLeft
' Squad directives: "jev <squad> <heart> <kind>". My own squad's is adopted; the other squad's
' tells me where they are going.
h = 0
while h < heardCount() and h < 4
  if heardSlot(h) mod 2 = selfTeam then
    t = heardText(h)
    if strWordCount(t) = 4 then
      if strEq(strWord(t, 0), strNew("jev")) then
        hSquad = strVal(strWord(t, 1))
        hObj = strVal(strWord(t, 2))
        hKind = strVal(strWord(t, 3))
        if hSquad = mySquad then
          lastDirectiveTick = worldTick
          if useRelay and worldTick - lastAnswerTick > 24 and hObj >= 0 and hObj < 16 then
            if hKind = 1 then
              jevGuard = hObj
              jevGuardUntil = worldTick + kHold
              jevObjective = -1
            else
              jevObjective = hObj
              jevObjectiveUntil = worldTick + kHold
              jevGuard = -1
            end if
          end if
        else
          otherSquadObj = hObj
          otherSquadTick = worldTick
        end if
      end if
    end if
  end if
  h = h + 1
wend
' Score the survival prediction ten seconds after it was made, and each applied objective
' fifteen seconds after it was applied (for off-policy scoring of prompt variants).
if survId > 0 then
  if worldTick - survTick >= 240 then
    survived = 1
    if livesLeft < survLives then
      survived = 0
    end if
    print "out t="; worldTick; " id="; survId; " psurv="; survP; " survived="; survived
    survId = 0
  end if
end if
if objOutId > 0 then
  if worldTick - objOutTick >= 360 then
    captured = 0
    if controlOwner(objOutHeart) = selfTeam then
      captured = 1
    end if
    print "objout t="; worldTick; " id="; objOutId; " k="; objOutK; " n="; objOutN; " heart="; objOutHeart; " kind="; objOutKind; " captured="; captured; " lost="; objOutLives - livesLeft; " ours="; ownedCount - objOutOwned
    objOutId = 0
  end if
end if
' Consume the last answer; act on it until the next lands. Refused or failed asks change nothing.
if jevReq > 0 then
  st = oraclePoll(jevReq)
  if st < 0 then
    print "fail t="; worldTick; " id="; jevReq
    jevReq = 0
  end if
  if st > 0 then
    lastAnswerTick = worldTick
    ansObj = oracleAnswer(jevReq, strNew("objective"))
    ansConf = oracleConfidence(jevReq, strNew("objective"))
    rawObj = ansObj
    if ansObj >= 0 then
      lastDirectiveTick = worldTick
      shoutTick = worldTick
      if useShuffle then
        nextRandom()
        ansObj = rngState mod (candN + 1)
        ansConf = 1000
      end if
      if useRule then
        ansObj = candN
        k = candN - 1
        while k >= 0
          if candKind(k) = 0 then
            if heartThreat(candHeart(k)) = 0 then
              ansObj = k
            end if
          end if
          k = k - 1
        wend
        ansConf = 1000
      end if
      if ansObj < candN and ansConf >= kConf then
        apply = 1
        if kMargin > 0 and useShuffle = 0 and useRule = 0 then
          pTop = oracleProbability(jevReq, strNew("objective"), strCatInt(strNew("C"), ansObj))
          pCur = oracleProbability(jevReq, strNew("objective"), strNew("current"))
          if pTop - pCur < kMargin then
            apply = 0
          end if
        end if
        if apply and useObjective then
          if candKind(ansObj) = 1 then
            jevGuard = candHeart(ansObj)
            jevGuardUntil = worldTick + kHold
            jevObjective = -1
          else
            jevObjective = candHeart(ansObj)
            jevObjectiveUntil = worldTick + kHold
            jevGuard = -1
          end if
          lastDirectiveTick = worldTick
          shoutTick = worldTick
        end if
      end if
      if objOutId = 0 and ansObj < candN then
        objOutId = jevReq
        objOutK = ansObj
        objOutN = candN + 1
        objOutHeart = candHeart(ansObj)
        objOutKind = candKind(ansObj)
        objOutTick = worldTick
        objOutLives = livesLeft
        objOutOwned = ownedCount
      end if
    end if
    ansRet = oracleAnswer(jevReq, strNew("retreat"))
    ansConf = oracleConfidence(jevReq, strNew("retreat"))
    if ansRet > 0 and ansRet < retCount and ansConf >= kConf and useRetreat then
      jevRetX = retX(ansRet)
      jevRetY = retY(ansRet)
      jevRetUntil = worldTick + kRetreatHold
    end if
    if ansRet = 0 then
      jevRetUntil = 0
    end if
    v = oracleAnswer(jevReq, strNew("survive"))
    if v >= 0 then
      if useDial then
        retreatDial = 1
        if v < kDialLow then
          retreatDial = 0
        end if
        if v > kDialHigh then
          retreatDial = 2
        end if
        dialUntil = worldTick + 96
      end if
      if survId = 0 then
        survId = jevReq
        survP = v
        survTick = worldTick
        survLives = livesLeft
      end if
    end if
    print "ans t="; worldTick; " id="; jevReq; " obj="; jevObjective; " guard="; jevGuard; " ansobj="; ansObj; " rawobj="; rawObj; " n="; candN + 1; " ret="; ansRet; " psurv="; v; " dial="; retreatDial
    jevReq = 0
  end if
end if
if worldTick >= dialUntil then
  retreatDial = 1
end if
' Relay: the asker repeats its squad's directive every two seconds while it is fresh.
if useRelay and worldTick - shoutTick >= 0 and (worldTick - shoutTick) mod 48 = 0 then
  if jevObjective >= 0 and worldTick < jevObjectiveUntil then
    shout(strCat(strCatInt(strCat(strCatInt(strNew("jev "), mySquad), strNew(" ")), jevObjective), strNew(" 0")))
  end if
  if jevGuard >= 0 and worldTick < jevGuardUntil then
    shout(strCat(strCatInt(strCat(strCatInt(strNew("jev "), mySquad), strNew(" ")), jevGuard), strNew(" 1")))
  end if
  if worldTick = shoutTick and shoutTick > 0 and worldTick >= jevObjectiveUntil and worldTick >= jevGuardUntil then
    ' "Keep current": nothing to adopt, but squadmates should know their asker is alive.
    ' (shoutTick > 0: only after an answer; at tick 0 every cog would otherwise shout and the
    ' baseline's turn-to-speech habit would make the file play differently without an oracle.)
    shout(strCat(strCatInt(strNew("jev "), mySquad), strNew(" -1 0")))
  end if
end if

' Where we want to be. Later rules override earlier ones; one walkTo is issued at the end.
goalX = selfX
goalY = selfY
holding = 0
if carrying then
  if ownHeartStolen and thief >= 0 then
    goalX = playerX(thief)
    goalY = playerY(thief)
  else
    goalX = homeX
    goalY = homeY
  end if
else
  if thief >= 0 then
    goalX = playerX(thief)
    goalY = playerY(thief)
  else
    goalX = heartX
    goalY = heartY
  end if
end if

' Territory: two squads of four. The target is a pure function of public heart ownership and
' the squad number, so all four members (even one that has just respawned) choose the same
' heart with no communication. Squad 0 works outward from above home, squad 1 from below
' (mirrored for blue, so the two teams play the half turn of each other).
objective = -1
if heartCount() > 0 then
  member = (selfId / 2) mod 8
  squad = member / 4
  seat = member mod 4
  otherTarget = -1
  candCount = 0
  candCost0 = 2147483647
  candCost1 = 2147483647
  candCost2 = 2147483647
  pass = 0
  while pass < 2
    refY = homeY - 1500
    if pass = 1 then
      refY = homeY + 1500
    end if
    if selfTeam = 1 then
      ' Mirror play: blue's first squad works from below home, the half turn of red's.
      refY = 4000 - refY
    end if
    choice = -1
    choiceCost = 2147483647
    j = 0
    while j < heartCount() and j < 16
      if controlOwner(j) <> selfTeam and j <> otherTarget then
        dx = (controlX(j) - homeX) / 8
        dy = (controlY(j) - refY) / 8
        cost = dx * dx + dy * dy
        if controlOwner(j) = -1 then
          cost = cost - 20000
        end if
        if pass = squad and avoidUntil(j) > worldTick then
          cost = cost + 4000000
        end if
        if pass = squad then
          ' Keep the three cheapest as the oracle's capture candidates.
          if cost < candCost0 then
            candCost2 = candCost1
            cheap2 = cheap1
            candCost1 = candCost0
            cheap1 = cheap0
            candCost0 = cost
            cheap0 = j
          else
            if cost < candCost1 then
              candCost2 = candCost1
              cheap2 = cheap1
              candCost1 = cost
              cheap1 = j
            else
              if cost < candCost2 then
                candCost2 = cost
                cheap2 = j
              end if
            end if
          end if
        end if
        if cost < choiceCost then
          choice = j
          choiceCost = cost
        end if
      end if
      j = j + 1
    wend
    if pass = squad then
      objective = choice
    else
      if pass < squad then
        otherTarget = choice
      end if
    end if
    pass = pass + 1
  wend
  if objective < 0 and otherTarget >= 0 then
    objective = otherTarget
  end if
  ' Jev's objective wins while it is fresh and still not ours.
  if jevObjective >= 0 and useObjective and worldTick < jevObjectiveUntil then
    if jevObjective < heartCount() then
      if controlOwner(jevObjective) <> selfTeam then
        objective = jevObjective
      end if
    end if
  end if
  if objective >= 0 then
    hx = controlX(objective)
    hy = controlY(objective)
    goalX = hx
    goalY = hy
    ' Seats 0 and 1 stand in the ring (capturer and backup). Seats 2 and 3 cover from outside
    ' it on the opposing side, and step in if nobody on our team is capturing.
    if seat >= 2 then
      capturing = controlCaptureTeam(objective) = selfTeam
      if capturing then
        idleCapture = 0
      else
        idleCapture = idleCapture + 1
      end if
      dx = hx - selfX
      dy = hy - selfY
      if dx * dx + dy * dy > 640000 or idleCapture < 96 then
        side = 1
        if seat = 3 then
          side = -1
        end if
        ax = 3200 - hx
        ay = 2000 - hy
        if selfTeam = 0 then
          ax = ax + 1200
        else
          ax = ax - 1200
        end if
        isqrt(ax * ax + ay * ay)
        if root > 0 then
          goalX = hx + (ax * 3 - ay * 2 * side) * 90 / root
          goalY = hy + (ay * 3 + ax * 2 * side) * 90 / root
        end if
      end if
    end if
    dx = goalX - selfX
    dy = goalY - selfY
    if dx * dx + dy * dy < 8100 then
      holding = 1
    end if
  end if
end if

' Remember seen supplies for ten seconds and equip when it is safe to.
i = 0
while i < pickupCount() and i < 32
  if pickupVisible(i) then
    pickupMemoryX(i) = pickupX(i)
    pickupMemoryY(i) = pickupY(i)
    pickupMemoryKind(i) = pickupKind(i)
    pickupMemoryTick(i) = worldTick + 1
  end if
  i = i + 1
wend
if not carrying and thief < 0 then
  nearest = -1
  nearestCost = 4840000
  j = 0
  while j < pickupCount() and j < 32
    if pickupMemoryTick(j) > 0 and worldTick - pickupMemoryTick(j) < 240 then
      kind = pickupMemoryKind(j)
      wanted = (kind = 0 and not hasGrenade) or (kind = 2 and selfHp < 3) or (kind = 3 and armorHp < 3 and selfHp = 3)
      if wanted then
        dx = pickupMemoryX(j) - selfX
        dy = pickupMemoryY(j) - selfY
        cost = dx * dx + dy * dy
        if kind = 2 and selfHp = 1 then
          ' A medkit is worth a whole life to a cog on one hit point.
          cost = cost / 4
        end if
        if cost < 10000 and not pickupVisible(j) then
          pickupMemoryTick(j) = 0
        else
          if cost < nearestCost then
            nearest = j
            nearestCost = cost
          end if
        end if
      end if
    end if
    j = j + 1
  wend
  if nearest >= 0 and (best < 0 or bestCost > 1440000 or selfHp = 1) then
    goalX = pickupMemoryX(nearest)
    goalY = pickupMemoryY(nearest)
    holding = 0
  end if
end if

' Refuse a fight we are visibly losing: head for the heart that is far from them and near us.
' Jev's survival estimate moves the bar: 0 breaks off when even, 1 is the baseline, 2 is bolder.
if foesSeen > 0 and foesNear - friendsNear >= retreatDial and not carrying then
  cx = foeSumX / foesSeen
  cy = foeSumY / foesSeen
  away = -1
  awayScore = -2147483647
  j = 0
  while j < heartCount() and j < 16
    ex = (controlX(j) - cx) / 16
    ey = (controlY(j) - cy) / 16
    mx = (controlX(j) - selfX) / 16
    my = (controlY(j) - selfY) / 16
    score = ex * ex + ey * ey - (mx * mx + my * my) / 2
    if score > awayScore then
      away = j
      awayScore = score
    end if
    j = j + 1
  wend
  if away >= 0 then
    goalX = controlX(away)
    goalY = controlY(away)
    holding = 0
  end if
end if

' ---- Jev overrides on the goal. ----
' Guard: stand on one of our hearts that is under threat until the hold runs out.
if jevGuard >= 0 and useObjective and worldTick < jevGuardUntil and not carrying then
  if jevGuard < heartCount() then
    if controlOwner(jevGuard) = selfTeam then
      goalX = controlX(jevGuard)
      goalY = controlY(jevGuard)
      holding = 0
      dx = goalX - selfX
      dy = goalY - selfY
      if dx * dx + dy * dy < 8100 then
        holding = 1
      end if
    end if
  end if
end if
' Retreat: go where Jev chose for a few seconds.
if useRetreat and worldTick < jevRetUntil and not carrying then
  goalX = jevRetX
  goalY = jevRetY
  holding = 0
end if

' ---- Ask Jev. The squad question goes to one asker per squad; a cog in danger asks for itself. ----
wantSquad = 0
wantSelf = 0
if jevReq = 0 and oracleAvailable() and worldTick - lastAskTick >= 24 and askCount < 220 then
  canSquadAsk = 1
  if useLeader then
    canSquadAsk = 0
    if worldTick - lastDirectiveTick > kLeaderWait * mySeat then
      canSquadAsk = 1
    end if
    if mySeat = 0 then
      canSquadAsk = 1
    end if
  end if
  fp = (objective + 1) * 100 + foesNear * 10 + ownedCount
  if canSquadAsk then
    if jevEvent then
      wantSquad = 1
    end if
    if worldTick - lastSquadAsk >= kAskDelay then
      if fp <> lastFp then
        wantSquad = 1
      end if
      if worldTick - lastSquadAsk >= 240 then
        wantSquad = 1
      end if
    end if
  end if
  if useRetreat or useDial then
    if selfEvent then
      wantSelf = 1
    end if
    if foesNear > friendsNear and worldTick - lastSelfAsk >= 72 then
      wantSelf = 1
    end if
  end if
end if
if wantSquad or wantSelf then
  ' Shared facts, scale in the name.
  oracleState(strNew("seconds_elapsed"), worldTick / 24)
  oracleState(strNew("our_score"), ourScore24 / 24)
  oracleState(strNew("enemy_score"), theirScore24 / 24)
  oracleState(strNew("score_to_win"), 900)
  oracleState(strNew("hearts_ours"), ownedCount)
  oracleState(strNew("hearts_enemy"), enemyCount)
  oracleState(strNew("hearts_neutral"), neutralCount)
  oracleState(strNew("my_hp_of_3"), selfHp)
  oracleState(strNew("my_lives_left"), livesLeft)
  oracleState(strNew("squadmates_within_12m"), friendsNear - 1)
  oracleState(strNew("enemies_within_26m"), foesNear)
  oracleState(strNew("fights_won"), fightsWon)
  oracleState(strNew("fights_total"), fightCount)
  if firstContact = 0 then
    oracleStateText(strNew("phase"), strNew("opening: no enemy contact yet"))
  else
    if worldTick - firstContact < 360 then
      oracleStateText(strNew("phase"), strNew("first contact"))
    else
      oracleStateText(strNew("phase"), strNew("midgame"))
    end if
  end if
  oracleStateText(strNew("limits"), strNew("I see only my forward cone; enemies not listed may exist. Teammates share nothing except shouts within 12 m. Hearts and scores are public."))
end if
if wantSquad then
  candCount = 0
  lastFp = fp
  lastSquadAsk = worldTick
  ' Candidates: the cheapest capture targets, a guard option, the big heart, a strike, keep current.
  if candCost0 < 2147483647 then
    candHeart(0) = cheap0
    candKind(0) = 0
    candCount = 1
  end if
  if candCost1 < 2147483647 and kCand >= 2 then
    candHeart(1) = cheap1
    candKind(1) = 0
    candCount = 2
  end if
  if candCost2 < 2147483647 and kCand >= 3 then
    candHeart(2) = cheap2
    candKind(2) = 0
    candCount = 3
  end if
  guardHeart = -1
  guardD2 = 2147483647
  bigHeart = -1
  strikeHeart = -1
  strikeD2 = 2147483647
  j = 0
  while j < heartCount() and j < 16
    dx = controlX(j) - selfX
    dy = controlY(j) - selfY
    d2 = (dx / 8) * (dx / 8) + (dy / 8) * (dy / 8)
    if controlOwner(j) = selfTeam then
      danger = heartThreat(j)
      if controlCaptureTeam(j) >= 0 then
        if controlCaptureTeam(j) <> selfTeam then
          danger = 1
        end if
      end if
      if danger and d2 < guardD2 then
        guardD2 = d2
        guardHeart = j
      end if
    else
      if controlPoints(j) > 1 then
        bigHeart = j
      end if
      if controlOwner(j) >= 0 and d2 < strikeD2 then
        strikeD2 = d2
        strikeHeart = j
      end if
    end if
    j = j + 1
  wend
  if useWide = 0 then
    guardHeart = -1
    bigHeart = -1
    strikeHeart = -1
  end if
  if guardHeart >= 0 then
    candHeart(candCount) = guardHeart
    candKind(candCount) = 1
    candCount = candCount + 1
  end if
  extra = bigHeart
  pass2 = 0
  while pass2 < 2
    if extra >= 0 then
      dup = 0
      k = 0
      while k < candCount
        if candHeart(k) = extra and candKind(k) = 0 then
          dup = 1
        end if
        k = k + 1
      wend
      if dup = 0 and candCount < 5 then
        candHeart(candCount) = extra
        candKind(candCount) = 0
        candCount = candCount + 1
      end if
    end if
    extra = strikeHeart
    pass2 = pass2 + 1
  wend
  hearts = strNew("")
  k = 0
  while k < candCount
    heartLine(candHeart(k))
    candLabel(k) = strCatInt(strNew("C"), k)
    if candKind(k) = 1 then
      candText(k) = strCat(strCat(strCat(strNew("defend "), label), strNew(": ")), line)
    else
      candText(k) = strCat(strCat(strCat(strNew("capture "), label), strNew(": ")), line)
    end if
    if k > 0 then
      hearts = strCat(hearts, strNew("; "))
    end if
    hearts = strCat(hearts, candText(k))
    k = k + 1
  wend
  oracleStateText(strNew("options"), hearts)
  if objective >= 0 then
    oracleStateText(strNew("current_objective"), strCatInt(strNew("H"), objective))
  end if
  oracleNote(strNew("Owned hearts keep scoring with nobody on them; first team to 900 points wins; a team with no lives left loses on the spot."))
  oracleNote(strNew("Measured over hundreds of matches here: a team that refuses fights when outnumbered and moves in groups of four won about 85% against every fight-everything style."))
  oracleNote(strNew("Measured here too: squads that split up lose. Prefer the objective my squadmates can reach with me, and do not send both squads to the same heart."))
  if useExamples then
    oracleNote(strNew("Example: two neutral hearts, one 10 m away with an enemy seen near it and one 25 m away and quiet. A squad of four at full hp takes the near one; a cog alone or at 1 hp takes the quiet one."))
    oracleNote(strNew("Example: we hold most hearts and the enemy is capturing one of ours 15 m away: defend it. Example: every nearby heart is ours and quiet: strike the nearest enemy-held heart."))
  end if
  oracleQuestion(strNew("objective"), 2, strNew("Which option should this squad work on for the next five seconds? Judge only this decision. Prefer what we can take or hold without walking into a bigger enemy group."))
  k = 0
  while k < candCount
    oracleCriterion(strNew("objective"), candLabel(k), candText(k))
    k = k + 1
  wend
  oracleCriterion(strNew("objective"), strNew("current"), strNew("keep the current objective (see `current_objective`)"))
  candN = candCount
end if
retCount = 0
if wantSelf then
  lastSelfAsk = worldTick
  line = strNew("gun ready")
  if gunWait > 0 then
    line = strNew("gun reloading")
  end if
  if armorHp > 0 then
    line = strCat(line, strNew(", armored"))
  end if
  if hasGrenade then
    line = strCat(line, strNew(", grenade"))
  end if
  if dmgTick > 0 then
    line = strCatInt(strCat(line, strNew(", took damage ")), (worldTick + 1 - dmgTick) / 24)
    line = strCat(line, strNew(" s ago"))
  end if
  oracleStateText(strNew("me"), line)
  enemies = strNew("none in view")
  shown = 0
  i = 1 - selfTeam
  while i < 16 and shown < 3
    if visible(i) then
      enemyLine(i)
      if shown = 0 then
        enemies = strCat(strCat(label, strNew(": ")), line)
      else
        enemies = strCat(strCat(strCat(enemies, strNew("; ")), label), strCat(strNew(": "), line))
      end if
      shown = shown + 1
    end if
    i = i + 2
  wend
  oracleStateText(strNew("enemies_in_view_now"), enemies)
  ' Where could I go? Code finds the places; Jev picks.
  retX(0) = goalX
  retY(0) = goalY
  retCount = 1
  oracleQuestion(strNew("retreat"), 2, strNew("This cog is hurt or outnumbered. Where should it go for the next three seconds? Judge only this decision."))
  oracleCriterion(strNew("retreat"), strNew("R0"), strNew("keep going toward the objective and keep fighting: I can win this or the objective matters more"))
  medkit = -1
  medD2 = 2147483647
  j = 0
  while j < pickupCount() and j < 32
    if pickupMemoryKind(j) = 2 and pickupMemoryTick(j) > 0 then
      if worldTick - pickupMemoryTick(j) < 600 then
        dx = pickupMemoryX(j) - selfX
        dy = pickupMemoryY(j) - selfY
        if dx * dx + dy * dy < medD2 then
          medD2 = dx * dx + dy * dy
          medkit = j
        end if
      end if
    end if
    j = j + 1
  wend
  if medkit >= 0 and selfHp < 3 then
    whereLine(pickupMemoryX(medkit) - selfX, pickupMemoryY(medkit) - selfY)
    retX(retCount) = pickupMemoryX(medkit)
    retY(retCount) = pickupMemoryY(medkit)
    oracleCriterion(strNew("retreat"), strCatInt(strNew("R"), retCount), strCat(strNew("go to the medkit I remember, restores my hp: "), line))
    retCount = retCount + 1
  end if
  mate = -1
  mateD2 = 2147483647
  i = selfTeam
  while i < 16
    if i <> selfId and visible(i) then
      dx = playerX(i) - selfX
      dy = playerY(i) - selfY
      if dx * dx + dy * dy < mateD2 and dx * dx + dy * dy > 90000 then
        mateD2 = dx * dx + dy * dy
        mate = i
      end if
    end if
    i = i + 2
  wend
  if mate >= 0 then
    whereLine(playerX(mate) - selfX, playerY(mate) - selfY)
    retX(retCount) = playerX(mate)
    retY(retCount) = playerY(mate)
    oracleCriterion(strNew("retreat"), strCatInt(strNew("R"), retCount), strCat(strNew("fall back to my nearest squadmate so we fight together: "), line))
    retCount = retCount + 1
  end if
  ownHeart = -1
  ownD2 = 2147483647
  j = 0
  while j < heartCount() and j < 16
    if controlOwner(j) = selfTeam then
      dx = (controlX(j) - selfX) / 8
      dy = (controlY(j) - selfY) / 8
      if dx * dx + dy * dy < ownD2 then
        ownD2 = dx * dx + dy * dy
        ownHeart = j
      end if
    end if
    j = j + 1
  wend
  if ownHeart >= 0 then
    whereLine(controlX(ownHeart) - selfX, controlY(ownHeart) - selfY)
    retX(retCount) = controlX(ownHeart)
    retY(retCount) = controlY(ownHeart)
    if heartThreat(ownHeart) then
      line = strCat(line, strNew(", but an enemy was seen near it"))
    end if
    oracleCriterion(strNew("retreat"), strCatInt(strNew("R"), retCount), strCat(strNew("fall back to the nearest heart we own, where teammates respawn: "), line))
    retCount = retCount + 1
  end if
end if
if wantSquad or wantSelf then
  oracleQuestion(strNew("survive"), 0, strNew("Will this cog still have all of its current lives ten seconds from now?"))
  oracleCriterion(strNew("survive"), strNew("true"), strNew("It is healthy or out of contact and is unlikely to be killed in the next ten seconds."))
  oracleCriterion(strNew("survive"), strNew("false"), strNew("It is hurt, outnumbered or walking into enemies and will probably lose a life within ten seconds."))
  jevReq = oracleAsk()
  if jevReq > 0 then
    lastAskTick = worldTick
    askCount = askCount + 1
    print "ask t="; worldTick; " id="; jevReq; " squad="; wantSquad; " self="; wantSelf; " cand="; candCount; " ret="; retCount; " seat="; mySeat
  else
    lastAskTick = worldTick - 12
    print "refused t="; worldTick
  end if
end if

' Facing with nothing to shoot: sweep, then turn to speech and sound.
if best < 0 then
  scan = (worldTick / 24 + selfId) mod 4
  lookX = goalX
  lookY = goalY
  if holding or scan = 1 then
    ' Sweep toward the enemy side first; blue's sweep is the half turn of red's.
    facing = 1 - 2 * selfTeam
    lookX = selfX + 2000 * facing
    lookY = selfY
    if scan = 1 then
      lookX = selfX
      lookY = selfY + 2000 * facing
    end if
    if scan = 2 then
      lookX = selfX - 2000 * facing
    end if
    if scan = 3 then
      lookX = selfX
      lookY = selfY - 2000 * facing
    end if
  end if
  if heardCount() > 0 then
    lookX = heardX(0)
    lookY = heardY(0)
  end if
  if soundCount() > 0 then
    soundBest = -1
    soundCost = 2147483647
    j = 0
    while j < soundCount() and j < 12
      cost = soundAge(j)
      if soundKind(j) = 1 or soundKind(j) = 2 then
        cost = cost - 48
      end if
      if cost < soundCost then
        soundBest = j
        soundCost = cost
      end if
      j = j + 1
    wend
    if soundBest >= 0 then
      bearing = soundDirection(soundBest)
      dxSound = 0
      dySound = 0
      if bearing = 0 or bearing = 1 or bearing = 7 then
        dxSound = 1000
      end if
      if bearing = 3 or bearing = 4 or bearing = 5 then
        dxSound = -1000
      end if
      if bearing = 1 or bearing = 2 or bearing = 3 then
        dySound = 1000
      end if
      if bearing = 5 or bearing = 6 or bearing = 7 then
        dySound = -1000
      end if
      lookX = selfX + dxSound
      lookY = selfY + dySound
    end if
  end if
  lookAt(lookX, lookY)
end if

if worldTick mod 360 = selfId * 21 then
  if best >= 0 then
    shout(strNew("Contact! Cover this lane."))
  else
    if foesNear - friendsNear >= 1 then
      shout(strNew("Too many. Falling back."))
    else
      shout(strNew("Moving with the squad."))
    end if
  end if
end if

' Footwork. In contact, move in short random legs across the line to the threat. A shot is only
' ordered at the start of a leg that lasts the whole windup, so our own movement is known.
moveX = goalX
moveY = goalY
inContact = best >= 0 and trenchId < 0
if inContact then
  threatX = playerX(best)
  threatY = playerY(best)
  ' Blocked for three ticks: let the engine's pathing take over for a second.
  if legTicks > 0 and myVX * myVX + myVY * myVY < 64 then
    stalled = stalled + 1
  else
    stalled = 0
  end if
  if stalled >= 3 then
    pathUntil = worldTick + 24
    stalled = 0
    legTicks = 0
  end if
  wantShot = gunWait = 0 and (hasSpray = 0 or bestCost < 640000)
  if worldTick >= pathUntil then
    if legTicks <= 0 or (wantShot and legTicks < 6) then
      if wantShot then
        planLeg(6, 9)
      else
        planLeg(3, 6)
      end if
    end if
    legTicks = legTicks - 1
    moveX = selfX + legX * 4
    moveY = selfY + legY * 4
    if holding then
      ' Stay inside the ring: turn back toward its centre when the leg would leave it.
      dx = selfX + legX * 2 - goalX
      dy = selfY + legY * 2 - goalY
      if dx * dx + dy * dy > 9000 then
        moveX = goalX
        moveY = goalY
        legTicks = 0
      end if
    end if
  end if
else
  legTicks = 0
  stalled = 0
end if
walkTo(moveX, moveY)

' Gun: the ray leaves six moves after the order, from wherever we then stand, along the
' direction locked one move from now. Aim where they will be, minus our own drift.
if best >= 0 then
  tx = playerX(best)
  ty = playerY(best)
  if lastSeen(best) = worldTick - 1 then
    tx = tx + (tx - oldX(best)) * 6
    ty = ty + (ty - oldY(best)) * 6
  end if
  if inContact and worldTick >= pathUntil then
    tx = tx - legX * 5
    ty = ty - legY * 5
  else
    tx = tx - myVX * 5
    ty = ty - myVY * 5
  end if
  ' Hold fire when a visible teammate stands in the line.
  clear = 1
  sx = tx - selfX
  sy = ty - selfY
  isqrt(sx * sx + sy * sy)
  reach = root
  if reach > 0 then
    i = 0
    while i < 16
      if i <> selfId and i mod 2 = selfTeam and visible(i) then
        ox = playerX(i) - selfX
        oy = playerY(i) - selfY
        along = (ox * sx + oy * sy) / reach
        across = (ox * sy - oy * sx) / reach
        if across < 0 then
          across = 0 - across
        end if
        if along > 0 and along < reach and across < 95 then
          clear = 0
        end if
      end if
      i = i + 1
    wend
  end if
  if hasSpray = 0 or bestCost < 640000 then
    if clear and gunWait = 0 then
      shootAt(tx, ty)
      gunWait = 25
      if armorHp > 0 or trenchId >= 0 or carrying then
        gunWait = 73
      end if
      if hasSpray then
        gunWait = 25
      end if
    else
      lookAt(tx, ty)
    end if
  else
    lookAt(tx, ty)
  end if
end if

i = 0
while i < 16
  if visible(i) then
    oldX(i) = playerX(i)
    oldY(i) = playerY(i)
    lastSeen(i) = worldTick
  end if
  i = i + 1
wend

' Grenade: match the charge to the distance, never onto a visible teammate.
if hasGrenade and best >= 0 then
  nx = playerX(best)
  ny = playerY(best)
  dx = nx - selfX
  dy = ny - selfY
  d2 = dx * dx + dy * dy
  safe = 1
  i = 0
  while i < 16
    if i mod 2 = selfTeam and visible(i) then
      fx = playerX(i) - nx
      fy = playerY(i) - ny
      if fx * fx + fy * fy < 202500 then
        safe = 0
      end if
    end if
    i = i + 1
  wend
  if safe and d2 > 160000 and d2 < 1562500 then
    isqrt(d2)
    need = (root - 150) * 24 / 1130 + 1
    if need < 1 then
      need = 1
    end if
    lookAt(nx, ny)
    chargeGrenade(grenadeCharge < need)
    if grenadeCharge >= need then
      shout(strNew("Grenade out!"))
    end if
  end if
end if

' Quiet approach to the objective when nothing is in sight but something was heard.
if best < 0 and soundCount() > 0 and objective >= 0 then
  dx = controlX(objective) - selfX
  dy = controlY(objective) - selfY
  if dx * dx + dy * dy < 810000 then
    sneak(1)
  end if
end if

lastX = selfX
lastY = selfY
